### PR TITLE
Add ZMQ interface for BitcoinD

### PR DESCRIPTION
**Pull request by bennyhodl**
Create the ZMQ interfaces and expose them through `BitcoinD`

Moved this upstream because I created a utility for [LND](https://github.com/bennyhodl/lnd-test-util) and needed to add a function to retrieve the ZMQ interface.

### CODE REVIEW

**Comment by RCasatta** [comment]
Thanks for the bump, I missed it.

Absolutely concept ack but I think we should add a `config.enable_zmq` or similar for enabling zmq which is false by default. My fear is using too many ports...

**Comment by bennyhodl** [comment]
@RCasatta added an optional config. Can rebase if it looks good

**Comment by RCasatta** [comment]
LGTM,
if you can squash and run `cargo fmt`

You can ignore CI error on windows, and also ignore clippy warnings.

**Comment by RCasatta** [comment]
ACK f69adc1ad3a5e77a64d2dd6596c8e2ab5ef08504

**Pull request merged**
